CREATE SEQUENCE product_sequence START WITH 10000 INCREMENT BY 1;
CREATE SEQUENCE firmware_sequence START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE presets_standard_sequence START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE quality_sequence START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE shared_sequence START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE user_sequence START WITH 20000 INCREMENT BY 1;
CREATE SEQUENCE library_sequence START WITH 1000 INCREMENT BY 1;